# Generated by Django 4.2 on 2023-12-26 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_reviewresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_general', '0002_alter_crmtaskresponsefile_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'product'), (2, 'category'), (3, 'money')])),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_kpis', to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor_kpis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPIItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'count'), (2, 'money')])),
                ('amount', models.IntegerField()),
                ('categories', models.ManyToManyField(related_name='kpi_items', to='product.category')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_items', to='crm_general.kpi')),
                ('products', models.ManyToManyField(related_name='kpi_items', to='product.asiaproduct')),
            ],
        ),
    ]
