# Generated by Django 4.2 on 2023-12-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_general', '0003_kpi_kpiitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmtaskresponse',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
