# Generated by Django 4.2 on 2023-12-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_general', '0004_crmtaskresponse_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmtaskfile',
            name='file',
            field=models.FileField(upload_to='tasks'),
        ),
        migrations.AlterField(
            model_name='crmtaskresponsefile',
            name='file',
            field=models.FileField(upload_to='response'),
        ),
    ]
