# Generated by Django 4.2 on 2024-01-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_general', '0005_alter_crmtaskfile_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmtask',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='crmtaskresponse',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ('-id',)},
        ),
    ]
