# Generated by Django 4.2 on 2024-01-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productprice_city'),
        ('crm_general', '0007_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='count',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crm_general.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_products', to='product.asiaproduct')),
            ],
        ),
    ]
