# Generated by Django 4.1 on 2024-01-06 14:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0004_pricetype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_alter_productprice_city'),
        ('crm_general', '0008_remove_inventory_count_remove_inventory_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerKPIPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('target_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dealer', 'target_month')},
            },
        ),
        migrations.CreateModel(
            name='ProductToBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_to_buy', to='crm_general.dealerkpiplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_plans', to='product.asiaproduct')),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_inventories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductToBuyCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_service.city')),
                ('product_to_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='crm_general.producttobuy')),
            ],
        ),
    ]
