# Generated by Django 4.1 on 2024-01-09 09:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0004_pricetype'),
        ('crm_general', '0009_dealerkpiplan_producttobuy_alter_inventory_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityProductToBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_service.city')),
                ('product_to_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_for_cities', to='crm_general.producttobuy')),
            ],
        ),
        migrations.CreateModel(
            name='CityProductToBuyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_count', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city_product_to_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='crm_general.cityproducttobuy')),
            ],
        ),
        migrations.CreateModel(
            name='DealerKPIPlanStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kpi_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='crm_general.dealerkpiplan')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductToBuyCount',
        ),
    ]
