# Generated by Django 4.2 on 2024-01-12 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_general', '0010_cityproducttobuy_cityproducttobuystat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmtaskresponse',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='crmtaskresponse',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='crmtaskresponse',
            name='task',
        ),
        migrations.RemoveField(
            model_name='crmtaskresponsefile',
            name='task',
        ),
        migrations.AddField(
            model_name='crmtask',
            name='executors',
            field=models.ManyToManyField(related_name='my_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmtaskfile',
            name='is_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crmtask',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('completed', 'completed'), ('not_completed', 'not_completed'), ('expired', 'expired'), ('repeat', 'repeat'), ('waiting', 'waiting')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='crmtask',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CRMTaskGrade',
        ),
        migrations.DeleteModel(
            name='CRMTaskResponse',
        ),
        migrations.DeleteModel(
            name='CRMTaskResponseFile',
        ),
    ]
