# Generated by Django 4.2 on 2024-01-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_general', '0011_remove_crmtaskresponse_executor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ('-created_at',)},
        ),
    ]
