# Generated by Django 4.2 on 2024-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_general', '0012_alter_inventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='uid',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=50),
        ),
    ]
