# Generated by Django 4.2 on 2024-01-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_general', '0012_alter_inventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryproduct',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
