# Generated by Django 4.2 on 2024-01-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_general', '0013_inventory_uid'),
        ('crm_general', '0013_inventoryproduct_rejected'),
    ]

    operations = [
    ]
