# Generated by Django 4.2 on 2024-01-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_general', '0015_remove_inventoryproduct_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('order', 'Заказ'), ('balance', 'Пополнение баланса')], max_length=20)),
                ('obj_status', models.CharField(max_length=100)),
            ],
        ),
    ]
