# Generated by Django 4.2 on 2024-02-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_general', '0016_autonotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonotification',
            name='obj_status',
            field=models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('sent', 'sent'), ('wait', 'wait'), ('rejected', 'rejected'), ('success', 'success')], max_length=20),
        ),
    ]
