# Generated by Django 4.2 on 2024-03-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_general', '0017_alter_autonotification_obj_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonotification',
            name='per_cent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='autonotification',
            name='obj_status',
            field=models.CharField(blank=True, choices=[('created', 'created'), ('paid', 'paid'), ('sent', 'sent'), ('wait', 'wait'), ('rejected', 'rejected'), ('success', 'success')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='autonotification',
            name='status',
            field=models.CharField(choices=[('order', 'Заказ'), ('balance', 'Пополнение баланса'), ('feedback', 'Отзыв'), ('motivation', 'Мотивация'), ('kpi', 'KPI'), ('birthday', 'День рождения')], max_length=20),
        ),
    ]
