# Generated by Django 4.2 on 2024-03-08 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_asiaproduct_made_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_general', '0018_autonotification_per_cent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonotification',
            name='status',
            field=models.CharField(choices=[('order', 'Заказ'), ('balance', 'Пополнение баланса'), ('feedback', 'Отзыв'), ('motivation', 'Мотивация'), ('kpi', 'KPI'), ('birthday', 'День рождения'), ('recommendation', 'Рекомендация')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_created', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(related_name='recommendations', to='product.asiaproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
