# Generated by Django 4.2 on 2024-03-11 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_asiaproduct_made_in'),
        ('crm_general', '0019_alter_autonotification_status_productrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrecommendation',
            name='products',
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='product',
            field=models.ForeignKey(default=388, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='product.asiaproduct'),
            preserve_default=False,
        ),
    ]
