# Generated by Django 4.1 on 2023-11-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="banner_id",
            new_name="link_id",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="order_status",
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
