# Generated by Django 4.2 on 2024-07-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceHistory',
        ),
    ]
