# Generated by Django 4.2 on 2024-07-16 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_balancehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireBaseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
