# Generated by Django 4.1 on 2023-11-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_rename_banner_id_notification_link_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealerprofile",
            name="notification",
            field=models.BooleanField(default=True),
        ),
    ]
