# Generated by Django 4.1 on 2023-12-21 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_balancehistory_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('order', 'Заказ'), ('news', 'Новости'), ('action', 'Акция'), ('notif', 'Оповещение'), ('chat', 'Чат'), ('balance', 'Пополнение баланса'), ('motivation', 'Мотивация')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='CRMNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dispatch_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('order', 'Заказ'), ('news', 'Новости'), ('action', 'Акция'), ('notif', 'Оповещение'), ('chat', 'Чат'), ('balance', 'Пополнение баланса'), ('motivation', 'Мотивация')], default='notif', max_length=100)),
                ('link_id', models.CharField(max_length=100)),
                ('is_push', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(related_name='crm_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_notification', to='account.crmnotification'),
        ),
    ]
