# Generated by Django 4.1 on 2023-11-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_rename_notification_dealerprofile_push_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_push",
            field=models.BooleanField(default=False),
        ),
    ]
