# Generated by Django 4.1 on 2023-12-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_notification_status_crmnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmnotification',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='notification'),
        ),
    ]
