# Generated by Django 4.1 on 2023-11-25 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_notification_is_push"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dealerstore",
            old_name="user",
            new_name="dealer",
        ),
    ]
