# Generated by Django 4.1 on 2023-12-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_crmnotification_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmnotification',
            name='is_push',
        ),
        migrations.RemoveField(
            model_name='crmnotification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='crmnotification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
