# Generated by Django 4.1 on 2023-11-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_rename_user_dealerstore_dealer"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalancePlus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_moderation", models.BooleanField(default=False)),
                ("is_success", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "dealer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="account.dealerprofile",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="wallet",
            old_name="amount",
            new_name="amount_1c",
        ),
        migrations.AddField(
            model_name="wallet",
            name="amount_crm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("order", "Заказ"),
                    ("news", "Новости"),
                    ("action", "Акция"),
                    ("notif", "Оповещение"),
                    ("chat", "Чат"),
                    ("balance", "Пополнение баланса"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BalancePlusFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="balance_plus_images")),
                (
                    "balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="account.balanceplus",
                    ),
                ),
            ],
        ),
    ]
