# Generated by Django 4.2 on 2023-12-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_dealerprofile_birthday'),
        ('account', '0006_remove_crmnotification_is_push_and_more'),
    ]

    operations = [
    ]
