# Generated by Django 4.1 on 2023-12-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("general_service", "0004_rename_city_cashbox_stock"),
        ("account", "0007_balanceplus_rename_amount_wallet_amount_1c_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealerstore",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="general_service.city",
            ),
        ),
    ]
