# Generated by Django 4.1 on 2023-12-07 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("general_service", "0004_rename_city_cashbox_stock"),
        ("account", "0008_alter_dealerstore_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="general_service.stock",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("director", "Директор"),
                    ("rop", "РОП"),
                    ("manager", "Менеджер"),
                    ("marketer", "Маркетолог"),
                    ("accountant", "Бухгалтер"),
                    ("dealer", "Дилер"),
                    ("warehouse", "Зав. Склад"),
                    ("dealer_1c", "dealer_1c"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
