# Generated by Django 4.2 on 2023-12-24 11:08

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0001_initial'),
        ('account', '0008_alter_balancehistory_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmnotification',
            name='cities',
            field=models.ManyToManyField(related_name='crm_notifications', to='general_service.city'),
        ),
        migrations.AddField(
            model_name='crmnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crmnotification',
            name='groups',
            field=models.ManyToManyField(related_name='crm_notifications', to='account.dealerstatus'),
        ),
        migrations.AlterField(
            model_name='crmnotification',
            name='link_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crmnotification',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='crm_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
