# Generated by Django 4.1 on 2023-12-07 15:48

import account.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_staffprofile_stock_alter_myuser_status"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="myuser",
            managers=[
                ("objects", account.models.MyUserManager()),
            ],
        ),
    ]
