# Generated by Django 4.2 on 2023-12-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0001_initial'),
        ('account', '0009_crmnotification_cities_crmnotification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmnotification',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='crm_notifications', to='general_service.city'),
        ),
        migrations.AlterField(
            model_name='crmnotification',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='crm_notifications', to='account.dealerstatus'),
        ),
    ]
