# Generated by Django 4.2 on 2024-01-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0004_pricetype'),
        ('account', '0010_alter_crmnotification_cities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancehistory',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='balanceplus',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='dealerprofile',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_profiles', to='general_service.pricetype'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.CharField(blank=True, choices=[('main_director', 'Директор'), ('director', 'Ком Директор'), ('rop', 'РОП'), ('manager', 'Менеджер'), ('marketer', 'Маркетолог'), ('accountant', 'Бухгалтер'), ('dealer', 'Дилер'), ('warehouse', 'Зав. Склад'), ('dealer_1c', 'dealer_1c')], max_length=20, null=True),
        ),
    ]
