# Generated by Django 4.2 on 2024-01-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_balancehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
