# Generated by Django 4.2 on 2024-01-06 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_dealerprofile_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.CharField(blank=True, choices=[('main_director', 'Директор'), ('director', 'Ком Директор'), ('rop', 'РОП'), ('manager', 'Менеджер'), ('marketer', 'Маркетолог'), ('accountant', 'Бухгалтер'), ('dealer', 'Дилер'), ('warehouse', 'Зав. Склад'), ('dealer_1c', 'dealer_1c'), ('hr', 'HR менеджер')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='StaffMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('hired', 'Принят на работу'), ('fired', 'Уволен'), ('vacation', 'Отпуск'), ('restored', 'Востановлен')], default='new', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
