# Generated by Django 4.2 on 2024-01-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_myuser_status_staffmagazine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmnotification',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='crmnotification',
            name='groups',
        ),
        migrations.AddField(
            model_name='crmnotification',
            name='dealer_profiles',
            field=models.ManyToManyField(blank=True, related_name='crm_notifications', to='account.dealerprofile'),
        ),
    ]
