# Generated by Django 4.2 on 2024-01-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_crmnotification_cities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmnotification',
            name='users',
        ),
    ]
