# Generated by Django 4.1 on 2024-01-10 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_crmnotification_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='managers',
            field=models.ManyToManyField(related_name='dealer_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
