# Generated by Django 4.2 on 2024-01-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_myuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerprofile',
            name='discount',
        ),
    ]
