# Generated by Django 4.1 on 2024-01-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_dealerprofile_managers'),
        ('account', '0017_remove_dealerprofile_discount'),
    ]

    operations = [
    ]
