# Generated by Django 4.2 on 2024-01-11 08:33

from django.conf import settings
from django.db import migrations, models
import general_service.compress


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_merge_20240110_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropprofile',
            name='managers',
            field=models.ManyToManyField(related_name='managers', to='account.managerprofile'),
        ),
        migrations.AlterField(
            model_name='crmnotification',
            name='image',
            field=general_service.compress.WEBPField(blank=True, null=True, upload_to=general_service.compress.notification_image_folder),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='dealer_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=general_service.compress.WEBPField(blank=True, null=True, upload_to=general_service.compress.user_image_folder),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.CharField(blank=True, choices=[('main_director', 'Директор'), ('director', 'Ком Директор'), ('rop', 'РОП'), ('manager', 'Менеджер'), ('marketer', 'Маркетолог'), ('accountant', 'Бухгалтер'), ('dealer', 'Дилер'), ('warehouse', 'Зав. Склад'), ('dealer_1c', 'dealer_1c'), ('hr', 'HR менеджер')], max_length=20, null=True),
        ),
    ]
