# Generated by Django 4.2 on 2024-01-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_myuser_status'),
        ('account', '0019_ropprofile_managers_alter_crmnotification_image_and_more'),
    ]

    operations = [
    ]
