# Generated by Django 4.2 on 2024-01-12 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0005_village_village_general_ser_slug_717783_idx'),
        ('account', '0020_merge_20240112_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_profiles', to='general_service.village'),
        ),
    ]
