# Generated by Django 4.2 on 2024-01-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_dealerprofile_city_dealerprofile_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='online',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='offline', max_length=20),
        ),
    ]
