# Generated by Django 4.2 on 2024-01-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_dealerprofile_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealerprofile',
            old_name='online',
            new_name='client_type',
        ),
    ]
