# Generated by Django 4.2 on 2024-01-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_rename_online_dealerprofile_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='firebase_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
