# Generated by Django 4.2 on 2024-01-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_myuser_firebase_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
