# Generated by Django 4.2 on 2024-01-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_myuser_firebase_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
