# Generated by Django 4.2 on 2024-01-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_verifycode_code'),
        ('account', '0025_managerprofile_is_main'),
    ]

    operations = [
    ]
