# Generated by Django 4.2 on 2024-01-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_merge_20240117_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerstatus',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
