# Generated by Django 4.2 on 2024-01-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_dealerstatus_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification',
        ),
    ]
