# Generated by Django 4.2 on 2024-01-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_remove_notification_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerstore',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
