# Generated by Django 4.2 on 2024-01-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_dealerstore_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseprofile',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
