# Generated by Django 4.2 on 2024-02-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_warehouseprofile_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmnotification',
            name='is_pushed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crmnotification',
            name='dealer_profiles',
            field=models.ManyToManyField(blank=True, null=True, related_name='crm_notifications', to='account.dealerprofile'),
        ),
    ]
