# Generated by Django 4.2 on 2024-03-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_alter_crmnotification_dealer_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('order', 'Заказ'), ('news', 'Новости'), ('action', 'Акция'), ('notif', 'Оповещение'), ('chat', 'Чат'), ('balance', 'Пополнение баланса'), ('motivation', 'Мотивация'), ('birthday', 'День рождения')], max_length=10, null=True),
        ),
    ]
