# Generated by Django 4.2 on 2024-03-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_alter_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('order', 'Заказ'), ('news', 'Новости'), ('action', 'Акция'), ('notif', 'Оповещение'), ('chat', 'Чат'), ('balance', 'Пополнение баланса'), ('motivation', 'Мотивация'), ('birthday', 'День рождения'), ('recommendation', 'Рекомендация'), ('kpi', 'KPI')], max_length=14, null=True),
        ),
    ]
