# Generated by Django 4.2 on 2024-03-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='per_cent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
