# Generated by Django 4.2 on 2024-06-28 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_by_user', models.BooleanField(default=True)),
                ('pds', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('fact_pds', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('month', models.DateField()),
                ('per_cent_pds', models.PositiveIntegerField(default=0)),
                ('per_cent_tmz', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akb', models.PositiveIntegerField(default=0)),
                ('month', models.DateField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mngr_kpis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerKPISVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('manager_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svds', to='crm_kpi.managerkpi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svds', to='product.asiaproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerKPIInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('svd', 'svd'), ('akb', 'akb'), ('tmz', 'tmz'), ('sch', 'sch'), ('pds', 'pds')], max_length=10)),
                ('per_cent', models.PositiveIntegerField(default=0)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('manager_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mngr_info', to='crm_kpi.managerkpi')),
            ],
        ),
        migrations.CreateModel(
            name='DealerKPIProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('fact_count', models.PositiveIntegerField(default=0)),
                ('fact_sum', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_products', to='crm_kpi.dealerkpi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_products', to='product.asiaproduct')),
            ],
        ),
    ]
