# Generated by Django 4.2 on 2024-01-16 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0011_alter_productimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('pds', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('fact_pds', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('month', models.DateField()),
                ('per_cent_pds', models.PositiveIntegerField(default=0)),
                ('per_cent_tmz', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerKPIPDSInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_cent', models.PositiveIntegerField(default=0)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerKPITMZInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_cent', models.PositiveIntegerField(default=0)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='DealerKPIProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('fact_count', models.PositiveIntegerField(default=0)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_products', to='crm_kpi.dealerkpi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_products', to='product.asiaproduct')),
            ],
        ),
    ]
