# Generated by Django 4.2 on 2024-01-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_kpi', '0002_managerkpipdsinfo_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerkpipdsinfo',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
