# Generated by Django 4.2 on 2024-01-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_kpi', '0003_alter_managerkpipdsinfo_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerkpiproduct',
            name='fact_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
