# Generated by Django 4.2 on 2024-01-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_kpi', '0004_dealerkpiproduct_fact_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerkpiproduct',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
