# Generated by Django 4.2 on 2024-01-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_kpi', '0005_dealerkpiproduct_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerkpiproduct',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
