# Generated by Django 4.2 on 2024-01-17 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_alter_productimage_image'),
        ('crm_kpi', '0006_alter_dealerkpiproduct_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akb', models.PositiveIntegerField(default=0)),
                ('month', models.DateField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mngr_kpis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerKPIInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('svd', 'svd'), ('akb', 'akb'), ('tmz', 'tmz'), ('sch', 'sch'), ('pds', 'pds')], max_length=10)),
                ('per_cent', models.PositiveIntegerField(default=0)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('manager_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mngr_info', to='crm_kpi.managerkpi')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerKPISVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('manager_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svds', to='crm_kpi.managerkpi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svds', to='product.asiaproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='ManagerKPIPDSInfo',
        ),
        migrations.DeleteModel(
            name='ManagerKPITMZInfo',
        ),
    ]
