# Generated by Django 4.2 on 2024-02-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_kpi', '0007_managerkpi_managerkpiinfo_managerkpisvd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerkpi',
            name='created_by_user',
            field=models.BooleanField(default=True),
        ),
    ]
