# Generated by Django 4.1 on 2023-12-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiaproduct',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
    ]
