# Generated by Django 4.1 on 2023-11-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="status",
        ),
        migrations.AddField(
            model_name="review",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
