# Generated by Django 4.1 on 2023-11-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_remove_review_status_review_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_moderation",
            field=models.BooleanField(default=False),
        ),
    ]
