# Generated by Django 4.1 on 2023-11-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_review_is_moderation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ("position",)},
        ),
        migrations.AddField(
            model_name="productimage",
            name="position",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
