# Generated by Django 4.2 on 2023-12-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcount',
            name='count_norm',
            field=models.IntegerField(default=0),
        ),
    ]
