# Generated by Django 4.1 on 2023-11-25 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0004_alter_productimage_options_productimage_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="likes_count",
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="ReviewLike",
        ),
    ]
