# Generated by Django 4.1 on 2023-11-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_alter_review_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="asiaproduct",
            name="is_hit",
            field=models.BooleanField(default=False),
        ),
    ]
