# Generated by Django 4.2 on 2024-01-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0004_pricetype'),
        ('product', '0007_reviewresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='general_service.pricetype'),
        ),
    ]
