# Generated by Django 4.1 on 2023-11-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_asiaproduct_is_hit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asiaproduct",
            old_name="link",
            new_name="video_link",
        ),
        migrations.AddField(
            model_name="asiaproduct",
            name="diagram",
            field=models.FileField(blank=True, null=True, upload_to="product_diagrams"),
        ),
    ]
