# Generated by Django 4.2 on 2024-01-05 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0004_pricetype'),
        ('product', '0008_productprice_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='general_service.city'),
        ),
    ]
