# Generated by Django 4.2 on 2024-01-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productprice_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiaproduct',
            name='diagram_link',
            field=models.TextField(blank=True),
        ),
    ]
