# Generated by Django 4.1 on 2023-11-25 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_productcount_arrival_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filtermaxmin",
            name="max_height",
        ),
        migrations.RemoveField(
            model_name="filtermaxmin",
            name="max_length",
        ),
        migrations.RemoveField(
            model_name="filtermaxmin",
            name="max_weight",
        ),
        migrations.RemoveField(
            model_name="filtermaxmin",
            name="max_width",
        ),
        migrations.RemoveField(
            model_name="filtermaxmin",
            name="min_height",
        ),
        migrations.RemoveField(
            model_name="filtermaxmin",
            name="min_length",
        ),
        migrations.RemoveField(
            model_name="filtermaxmin",
            name="min_weight",
        ),
        migrations.RemoveField(
            model_name="filtermaxmin",
            name="min_width",
        ),
    ]
