# Generated by Django 4.2 on 2024-01-12 12:52

from django.db import migrations
import general_service.compress


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_asiaproduct_diagram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=general_service.compress.WEBPField(upload_to=general_service.compress.product_image_folder),
        ),
    ]
