# Generated by Django 4.2 on 2024-01-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asiaproduct',
            options={'ordering': ('-id',)},
        ),
    ]
