# Generated by Django 4.1 on 2023-12-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_reviewimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprice",
            name="discount_status",
            field=models.CharField(
                choices=[("Per", "per"), ("Num", "Num")], default="Per", max_length=5
            ),
        ),
    ]
