# Generated by Django 4.2 on 2024-01-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_asiaproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiaproduct',
            name='made_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
