# Generated by Django 4.1 on 2023-12-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=40)),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Нал', 'Нал'), ('Без нал', 'Без нал')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
            ],
        ),
    ]
