# Generated by Django 4.1 on 2023-12-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_c', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocPay',
        ),
    ]
