# Generated by Django 4.2 on 2023-12-19 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_delete_ordermoney'),
        ('general_service', '0001_initial'),
        ('one_c', '0002_delete_docpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Нал', 'Нал'), ('Без нал', 'Без нал')], max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('uid', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_docs', to='general_service.cashbox')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_docs', to='order.myorder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
