# Generated by Django 4.2 on 2023-12-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_c', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydoc',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
