# Generated by Django 4.2 on 2023-12-19 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_c', '0004_moneydoc_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneydoc',
            name='order',
        ),
    ]
