# Generated by Django 4.2 on 2023-12-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_slug_alter_collection_slug'),
        ('one_c', '0005_remove_moneydoc_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementProduct1C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('warehouse_recipient_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('warehouse_sender_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovementProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mv_products', to='one_c.movementproduct1c')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mv_products', to='product.asiaproduct')),
            ],
        ),
    ]
