# Generated by Django 4.2 on 2023-12-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_c', '0006_movementproduct1c_movementproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementproduct1c',
            name='uid',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=50),
        ),
    ]
