# Generated by Django 4.2 on 2024-01-16 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_delete_reservation'),
        ('one_c', '0007_alter_movementproduct1c_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydoc',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_docs', to='order.myorder'),
        ),
    ]
