# Generated by Django 4.2 on 2024-01-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_c', '0008_moneydoc_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydoc',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
