# Generated by Django 4.2 on 2024-01-31 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0005_village_village_general_ser_slug_717783_idx'),
        ('one_c', '0009_moneydoc_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementproduct1c',
            name='warehouse_recipient_uid',
        ),
        migrations.RemoveField(
            model_name='movementproduct1c',
            name='warehouse_sender_uid',
        ),
        migrations.AddField(
            model_name='movementproduct1c',
            name='warehouse_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_movements', to='general_service.stock'),
        ),
        migrations.AddField(
            model_name='movementproduct1c',
            name='warehouse_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_movements', to='general_service.stock'),
        ),
    ]
