# Generated by Django 4.2 on 2024-06-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
