# Generated by Django 4.1 on 2023-11-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="price_uid",
        ),
        migrations.AddField(
            model_name="stock",
            name="price_uid",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
