# Generated by Django 4.2 on 2023-12-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
