# Generated by Django 4.1 on 2023-11-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("general_service", "0002_remove_city_price_uid_stock_price_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="price_uid",
        ),
        migrations.AddField(
            model_name="city",
            name="price_uid",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="cashbox",
            name="city",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_box",
                to="general_service.stock",
            ),
        ),
    ]
