# Generated by Django 4.1 on 2023-11-29 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("general_service", "0003_remove_stock_price_uid_city_price_uid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cashbox",
            old_name="city",
            new_name="stock",
        ),
    ]
