# Generated by Django 4.2 on 2024-01-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0005_village_village_general_ser_slug_717783_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetype',
            options={'ordering': ('-id',)},
        ),
    ]
