# Generated by Django 4.2 on 2024-06-28 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import general_service.compress


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_service', '0001_initial'),
        ('product', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Per', 'Per'), ('Sum', 'Sum')], default='Per', max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dealer_profiles', models.ManyToManyField(related_name='discount_d_profiles', to='account.dealerprofile')),
                ('products', models.ManyToManyField(related_name='discount_products', to='product.asiaproduct')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dealers', models.ManyToManyField(blank=True, related_name='motivations', to='account.dealerprofile')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MotivationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('category', 'category'), ('money', 'money'), ('product', 'product')], max_length=10)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('motivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='promotion.motivation')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=16, null=True)),
                ('slogan', models.CharField(blank=True, max_length=16, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='stories_files')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('dealer_profiles', models.ManyToManyField(related_name='stories', to='account.dealerprofile')),
                ('products', models.ManyToManyField(blank=True, related_name='stories', to='product.asiaproduct')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MotivationPresent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('money', 'Деньги'), ('text', 'Прочее')], default='money', max_length=10)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presents', to='promotion.motivationcondition')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('is_active', models.BooleanField(default=False)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_prices', to='general_service.city')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_prices', to='promotion.discount')),
                ('price_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_prices', to='general_service.pricetype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_prices', to='product.asiaproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_prices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_prods', to='promotion.motivationcondition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_prods', to='product.asiaproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_cats', to='product.category')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_cats', to='promotion.motivationcondition')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('image', general_service.compress.WEBPField(blank=True, null=True, upload_to=general_service.compress.banner_image_folder)),
                ('web_image', models.ImageField(blank=True, null=True, upload_to='banner-images')),
                ('video_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('show_date', models.BooleanField(default=False)),
                ('dealer_profiles', models.ManyToManyField(blank=True, related_name='banners', to='account.dealerprofile')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='promotion.discount')),
                ('motivation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='promotion.motivation')),
                ('products', models.ManyToManyField(blank=True, related_name='banners', to='product.asiaproduct')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
