# Generated by Django 4.1 on 2023-11-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0004_alter_productimage_options_productimage_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=300)),
                ("slogan", models.CharField(max_length=300)),
                ("text", models.TextField()),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="stories_files"),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="stories", to="product.asiaproduct"
                    ),
                ),
            ],
        ),
    ]
