# Generated by Django 4.1 on 2023-12-18 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_balancehistory_balance'),
        ('product', '0002_asiaproduct_is_discount'),
        ('general_service', '0001_initial'),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('discount_status', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_products', to='promotion.discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_products', to='product.asiaproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountDealerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_d_statuses', to='account.dealerstatus')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_d_statuses', to='promotion.discount')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_cities', to='general_service.city')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_cities', to='promotion.discount')),
            ],
        ),
    ]
