# Generated by Django 4.1 on 2023-12-03 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_alter_dealerstore_city"),
        ("product", "0013_alter_productprice_discount_status"),
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "completed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="account.dealerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TargetPresent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("product", "Товар"),
                            ("money", "Деньги"),
                            ("text", "Прочее"),
                        ],
                        default="money",
                        max_length=10,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presents",
                        to="promotion.target",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TargetPresentProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "present",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="present_products",
                        to="promotion.targetpresent",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="present_products",
                        to="product.asiaproduct",
                    ),
                ),
            ],
        ),
    ]
