# Generated by Django 4.1 on 2023-12-03 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_alter_productprice_discount_status"),
        ("promotion", "0002_target_targetpresent_targetpresentproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetpresent",
            name="money",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="targetpresent",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="present_products",
                to="product.asiaproduct",
            ),
        ),
        migrations.AddField(
            model_name="targetpresent",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="TargetPresentProduct",
        ),
    ]
