# Generated by Django 4.2 on 2023-12-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0001_initial'),
        ('account', '0003_balancehistory_balance'),
        ('product', '0004_alter_productimage_options_and_more'),
        ('promotion', '0003_conditioncategory_conditionproduct_motivation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountdealerstatus',
            name='dealer_status',
        ),
        migrations.RemoveField(
            model_name='discountdealerstatus',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='discountproduct',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='discountproduct',
            name='product',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='discount_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_status',
        ),
        migrations.AddField(
            model_name='discount',
            name='cities',
            field=models.ManyToManyField(related_name='discount_cities', to='general_service.city'),
        ),
        migrations.AddField(
            model_name='discount',
            name='dealer_statuses',
            field=models.ManyToManyField(related_name='discount_d_statuses', to='account.dealerstatus'),
        ),
        migrations.AddField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(related_name='discount_products', to='product.asiaproduct'),
        ),
        migrations.AddField(
            model_name='discount',
            name='status',
            field=models.CharField(choices=[('Per', 'Per'), ('Sum', 'Sum')], default='Per', max_length=5),
        ),
        migrations.DeleteModel(
            name='DiscountCity',
        ),
        migrations.DeleteModel(
            name='DiscountDealerStatus',
        ),
        migrations.DeleteModel(
            name='DiscountProduct',
        ),
    ]
