# Generated by Django 4.2 on 2023-12-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_remove_discountdealerstatus_dealer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
