# Generated by Django 4.2 on 2023-12-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_discount_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
