# Generated by Django 4.1 on 2023-12-20 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0001_initial'),
        ('product', '0004_alter_productimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion', '0006_alter_discount_end_date_alter_discount_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('video_url', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('web', 'web'), ('app', 'app')], default='web', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('cities', models.ManyToManyField(related_name='banners', to='general_service.city')),
                ('participants', models.ManyToManyField(related_name='banners', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(related_name='banners', to='product.asiaproduct')),
            ],
        ),
    ]
