# Generated by Django 4.2 on 2023-12-19 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0006_alter_discount_end_date_alter_discount_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivationpresent',
            name='motivation',
        ),
        migrations.AddField(
            model_name='motivationpresent',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presents', to='promotion.motivationcondition'),
        ),
    ]
