# Generated by Django 4.2 on 2023-12-19 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0007_remove_motivationpresent_motivation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditioncategory',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_cats', to='promotion.motivationcondition'),
        ),
        migrations.AlterField(
            model_name='conditionproduct',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_prods', to='promotion.motivationcondition'),
        ),
    ]
