# Generated by Django 4.1 on 2023-12-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0001_initial'),
        ('account', '0006_remove_crmnotification_is_push_and_more'),
        ('promotion', '0008_banner_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='participants',
        ),
        migrations.AddField(
            model_name='story',
            name='cities',
            field=models.ManyToManyField(related_name='stories', to='general_service.city'),
        ),
        migrations.AddField(
            model_name='story',
            name='dealer_groups',
            field=models.ManyToManyField(related_name='stories', to='account.dealerstatus'),
        ),
    ]
