# Generated by Django 4.2 on 2023-12-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0008_alter_conditioncategory_condition_and_more'),
        ('promotion', '0009_remove_banner_participants_story_cities_and_more'),
    ]

    operations = [
    ]
