# Generated by Django 4.2 on 2023-12-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_balancehistory_dealer'),
        ('promotion', '0010_merge_20231222_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationpresent',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='dealers',
            field=models.ManyToManyField(blank=True, related_name='motivations', to='account.dealerprofile'),
        ),
    ]
