# Generated by Django 4.2 on 2023-12-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0011_motivationpresent_expense_alter_motivation_dealers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivationpresent',
            name='product',
        ),
        migrations.AlterField(
            model_name='motivationpresent',
            name='status',
            field=models.CharField(choices=[('money', 'Деньги'), ('text', 'Прочее')], default='money', max_length=10),
        ),
    ]
