# Generated by Django 4.2 on 2023-12-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productimage_options_and_more'),
        ('promotion', '0012_remove_motivationpresent_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationpresent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='present_products', to='product.asiaproduct'),
        ),
    ]
