# Generated by Django 4.2 on 2023-12-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0013_motivationpresent_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivationpresent',
            name='product',
        ),
    ]
