# Generated by Django 4.2 on 2023-12-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0014_remove_motivationpresent_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='video_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='banner-files'),
        ),
    ]
