# Generated by Django 4.2 on 2023-12-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0015_remove_banner_video_url_banner_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='file',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner-images'),
        ),
        migrations.AddField(
            model_name='banner',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
