# Generated by Django 4.2 on 2024-01-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0016_remove_banner_file_banner_image_banner_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='image',
            new_name='file',
        ),
    ]
