# Generated by Django 4.2 on 2024-03-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0016_remove_banner_file_banner_image_banner_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
