# Generated by Django 4.2 on 2024-01-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_myuser_status_staffmagazine'),
        ('promotion', '0017_rename_image_story_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='status',
        ),
        migrations.AddField(
            model_name='banner',
            name='dealers',
            field=models.ManyToManyField(related_name='banners', to='account.dealerprofile'),
        ),
        migrations.AddField(
            model_name='banner',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='promotion.discount'),
        ),
        migrations.AddField(
            model_name='banner',
            name='motivation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='promotion.motivation'),
        ),
        migrations.AddField(
            model_name='banner',
            name='web_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner-images'),
        ),
    ]
