# Generated by Django 4.2 on 2024-01-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_myuser_status_staffmagazine'),
        ('promotion', '0018_remove_banner_cities_remove_banner_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='dealers',
            new_name='dealer_profiles',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='dealer_statuses',
        ),
        migrations.AddField(
            model_name='discount',
            name='dealer_profiles',
            field=models.ManyToManyField(related_name='discount_d_profiles', to='account.dealerprofile'),
        ),
    ]
