# Generated by Django 4.2 on 2024-01-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_myuser_status_staffmagazine'),
        ('product', '0009_alter_productprice_city'),
        ('promotion', '0019_rename_dealers_banner_dealer_profiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='dealer_profiles',
            field=models.ManyToManyField(blank=True, related_name='banners', to='account.dealerprofile'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='banners', to='product.asiaproduct'),
        ),
    ]
