# Generated by Django 4.2 on 2024-01-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_myuser_status_staffmagazine'),
        ('promotion', '0020_alter_banner_dealer_profiles_alter_banner_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='story',
            name='dealer_groups',
        ),
        migrations.AddField(
            model_name='story',
            name='dealer_profiles',
            field=models.ManyToManyField(related_name='stories', to='account.dealerprofile'),
        ),
    ]
