# Generated by Django 4.2 on 2024-01-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0021_remove_story_cities_remove_story_dealer_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
