# Generated by Django 4.2 on 2024-01-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0022_alter_banner_end_time_alter_banner_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='show_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
