# Generated by Django 4.2 on 2024-01-12 12:52

from django.db import migrations
import general_service.compress


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0023_banner_show_date_story_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=general_service.compress.WEBPField(blank=True, null=True, upload_to=general_service.compress.banner_image_folder),
        ),
    ]
