# Generated by Django 4.2 on 2024-01-15 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_alter_productimage_image'),
        ('promotion', '0024_alter_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('pds', models.DecimalField(decimal_places=2, max_digits=100)),
                ('month', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealerKPIProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_products', to='promotion.dealerkpi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_products', to='product.asiaproduct')),
            ],
        ),
    ]
