# Generated by Django 4.2 on 2024-01-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0025_dealerkpi_dealerkpiproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerkpi',
            name='fact_pds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='dealerkpi',
            name='per_cent_pds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dealerkpi',
            name='per_cent_tmz',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dealerkpiproduct',
            name='fact_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dealerkpi',
            name='pds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
