# Generated by Django 4.2 on 2024-01-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0027_managerkpipdsinfo_managerkpitmzinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerkpi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dealerkpiproduct',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='dealerkpiproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='ManagerKPIPDSInfo',
        ),
        migrations.DeleteModel(
            name='ManagerKPITMZInfo',
        ),
        migrations.DeleteModel(
            name='DealerKPI',
        ),
        migrations.DeleteModel(
            name='DealerKPIProduct',
        ),
    ]
