# Generated by Django 4.2 on 2024-01-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0028_remove_dealerkpi_user_remove_dealerkpiproduct_kpi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-id',)},
        ),
    ]
