# Generated by Django 4.2 on 2024-01-24 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_alter_asiaproduct_options'),
        ('general_service', '0005_village_village_general_ser_slug_717783_idx'),
        ('promotion', '0029_alter_banner_options_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_prices', to='general_service.city')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_prices', to='promotion.discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_prices', to='product.asiaproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_prices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
