# Generated by Django 4.2 on 2024-01-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0030_discountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountprice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
