# Generated by Django 4.2 on 2024-01-24 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0005_village_village_general_ser_slug_717783_idx'),
        ('promotion', '0031_discountprice_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountprice',
            name='price_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_prices', to='general_service.pricetype'),
        ),
        migrations.AlterField(
            model_name='discountprice',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_prices', to='general_service.city'),
        ),
    ]
