# Generated by Django 4.2 on 2024-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_asiaproduct_made_in'),
        ('promotion', '0032_discountprice_price_type_alter_discountprice_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='stories', to='product.asiaproduct'),
        ),
    ]
