# Generated by Django 4.2 on 2024-01-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0033_alter_story_products'),
        ('promotion', '0033_story_created_at_alter_story_products'),
    ]

    operations = [
    ]
