# Generated by Django 4.2 on 2024-02-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0034_merge_20240130_1003'),
        ('promotion', '0034_merge_20240130_2034'),
    ]

    operations = [
    ]
