# Generated by Django 4.2 on 2024-02-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0035_merge_20240202_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slogan',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=16),
        ),
    ]
