# Generated by Django 4.2 on 2024-02-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0036_alter_story_slogan_alter_story_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
