# Generated by Django 4.2 on 2024-02-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0037_alter_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slogan',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
