# Generated by Django 4.2 on 2024-02-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0038_alter_story_slogan_alter_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slogan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
