# Generated by Django 4.2 on 2024-03-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0017_motivation_description'),
        ('promotion', '0040_alter_story_slogan'),
    ]

    operations = [
    ]
