# Generated by Django 4.1 on 2024-01-13 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_alter_productimage_image'),
        ('general_service', '0005_village_village_general_ser_slug_717783_idx'),
        ('crm_stat', '0002_alter_stat_amount_alter_stat_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general_service.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=500)),
                ('vendor_code', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.collection')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.asiaproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('spent_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('count', models.PositiveIntegerField()),
                ('purchases_count', models.PositiveIntegerField(default=0)),
                ('avg_check', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('product_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='crm_stat.productstat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('city_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='crm_stat.citystat')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general_service.stock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('city_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='crm_stat.citystat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTransactionsStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='crm_stat.stockstat')),
                ('user_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='crm_stat.userstat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='stat',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='user',
        ),
        migrations.DeleteModel(
            name='PDS',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.AddField(
            model_name='purchasestat',
            name='stock_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='crm_stat.stockstat'),
        ),
        migrations.AddField(
            model_name='purchasestat',
            name='user_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='crm_stat.userstat'),
        ),
    ]
