# Generated by Django 4.1 on 2024-01-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_stat', '0003_citystat_productstat_purchasestat_stockstat_userstat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citystat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchasestat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockstat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usertransactionsstat',
            name='date',
            field=models.DateField(),
        ),
    ]
