# Generated by Django 4.1 on 2024-01-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_stat', '0004_alter_citystat_date_alter_productstat_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstat',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
