# Generated by Django 4.1 on 2024-01-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_stat', '0005_stockstat_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='citystat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
