# Generated by Django 4.1 on 2024-01-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_stat', '0006_citystat_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citystat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='productstat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchasestat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stockstat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userstat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='usertransactionsstat',
            name='created_at',
        ),
        migrations.AddField(
            model_name='citystat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productstat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockstat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userstat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
