# Generated by Django 4.2 on 2024-01-21 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_stat', '0010_alter_stockgroupstat_stat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstat',
            name='city_stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='crm_stat.citystat'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='city_stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='crm_stat.citystat'),
        ),
    ]
