# Generated by Django 4.2 on 2024-01-24 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_service', '0005_village_village_general_ser_slug_717783_idx'),
        ('product', '0012_alter_asiaproduct_options'),
        ('crm_stat', '0012_alter_usertransactionsstat_bank_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstat',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productstat',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='productstat',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockstat',
            name='city_stat',
        ),
        migrations.RemoveField(
            model_name='stockstat',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='userstat',
            name='city_stat',
        ),
        migrations.RemoveField(
            model_name='userstat',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='stockgroupstat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='purchasestat',
            name='product_stat',
        ),
        migrations.RemoveField(
            model_name='purchasestat',
            name='stock_stat',
        ),
        migrations.RemoveField(
            model_name='purchasestat',
            name='user_stat',
        ),
        migrations.RemoveField(
            model_name='usertransactionsstat',
            name='stock_stat',
        ),
        migrations.RemoveField(
            model_name='usertransactionsstat',
            name='user_stat',
        ),
        migrations.AddField(
            model_name='purchasestat',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='product.asiaproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasestat',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='general_service.stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasestat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockgroupstat',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_stats', to='general_service.stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertransactionsstat',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='general_service.stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertransactionsstat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stockgroupstat',
            unique_together={('stat_type', 'stock', 'date')},
        ),
        migrations.DeleteModel(
            name='CityStat',
        ),
        migrations.DeleteModel(
            name='ProductStat',
        ),
        migrations.DeleteModel(
            name='UserStat',
        ),
        migrations.RemoveField(
            model_name='stockgroupstat',
            name='stock_stat',
        ),
        migrations.DeleteModel(
            name='StockStat',
        ),
    ]
