# Generated by Django 4.2 on 2024-06-28 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_service', '0001_initial'),
        ('product', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='account.dealerprofile')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='general_service.stock')),
            ],
        ),
        migrations.CreateModel(
            name='MainOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('status', models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('sent', 'sent'), ('partial', 'partial'), ('rejected', 'rejected'), ('success', 'success')], default='created', max_length=15)),
                ('type_status', models.CharField(blank=True, choices=[('cash', 'Наличка'), ('visa', 'Виза'), ('wallet', 'Кошелек'), ('kaspi', 'Каспи')], max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_doc_uid', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=50)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_orders', to='account.dealerprofile')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_orders', to='general_service.stock')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gmail', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('status', models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('sent', 'sent'), ('wait', 'wait'), ('rejected', 'rejected'), ('success', 'success')], default='created', max_length=15)),
                ('type_status', models.CharField(blank=True, choices=[('cash', 'Наличка'), ('visa', 'Виза'), ('wallet', 'Кошелек'), ('kaspi', 'Каспи')], max_length=15, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='account.dealerprofile')),
                ('main_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.mainorder')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='general_service.stock')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_orders', to='order.myorder')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReturnOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'created'), ('success', 'success'), ('rejected', 'rejected')], default='created', max_length=8)),
                ('count', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='product.asiaproduct')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.returnorder')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnOrderProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='return-products')),
                ('return_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='order.returnorderproduct')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order-check')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_receipts', to='order.myorder')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('count', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='order-product')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('is_checked', models.BooleanField(default=False)),
                ('ab_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products', to='product.asiaproduct')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products', to='product.category')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='order.myorder')),
            ],
        ),
        migrations.CreateModel(
            name='MainOrderReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='main-order-check')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='order.mainorder')),
            ],
        ),
        migrations.CreateModel(
            name='MainOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('ab_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_order_products', to='product.asiaproduct')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.mainorder')),
            ],
        ),
        migrations.CreateModel(
            name='MainOrderCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='order.mainorder')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='order.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='product.asiaproduct')),
            ],
        ),
    ]
