# Generated by Django 4.1 on 2023-11-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_rename_user_dealerstore_dealer"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="myorder",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="account.dealerprofile",
            ),
        ),
    ]
