# Generated by Django 4.2 on 2024-07-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainordercode',
            old_name='user',
            new_name='main_order',
        ),
    ]
