# Generated by Django 4.2 on 2023-12-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_myorder_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderMoney',
        ),
    ]
