# Generated by Django 4.1 on 2023-11-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_orderproduct_discount_alter_myorder_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
