# Generated by Django 4.2 on 2024-07-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_user_mainordercode_main_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainorderproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='mainorderproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='mainorderproduct',
            name='unit_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
