# Generated by Django 4.2 on 2023-12-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_delete_ordermoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Оплачено', 'Оплачено'), ('Отправлено', 'Отправлено'), ('Ожидание', 'Ожидание'), ('Отказано', 'Отказано'), ('Успешно', 'Успешно')], default='Новый', max_length=15),
        ),
    ]
