# Generated by Django 4.2 on 2023-12-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_service', '0001_initial'),
        ('order', '0004_alter_myorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='general_service.stock'),
        ),
    ]
