# Generated by Django 4.1 on 2023-11-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("general_service", "0004_rename_city_cashbox_stock"),
        ("order", "0004_cart_remove_myorder_city_pay_myorder_cash_box_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="stock",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="general_service.stock",
            ),
        ),
    ]
