# Generated by Django 4.1 on 2023-12-02 00:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_alter_cart_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myorder",
            name="author_image",
        ),
    ]
