# Generated by Django 4.2 on 2023-12-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_cartproduct_created_at_alter_cart_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='type_status',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('visa', 'visa'), ('wallet', 'wallet'), ('kaspi', 'kaspi')], max_length=15, null=True),
        ),
    ]
