# Generated by Django 4.2 on 2023-12-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_myorder_type_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('sent', 'sent'), ('wait', 'wait'), ('rejected', 'rejected'), ('success', 'success')], default='created', max_length=15),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('success', 'success'), ('rejected', 'rejected')], default='rejected', max_length=10),
        ),
    ]
