# Generated by Django 4.1 on 2023-12-07 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("general_service", "0004_rename_city_cashbox_stock"),
        ("order", "0006_remove_myorder_author_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myorder",
            name="cash_box",
        ),
        migrations.CreateModel(
            name="OrderMoney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "uid",
                    models.CharField(
                        default="00000000-0000-0000-0000-000000000000", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cash_box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_moneys",
                        to="general_service.cashbox",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_moneys",
                        to="order.myorder",
                    ),
                ),
            ],
        ),
    ]
