# Generated by Django 4.2 on 2024-01-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderproduct_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='type_status',
            field=models.CharField(blank=True, choices=[('cash', 'Наличка'), ('visa', 'Виза'), ('wallet', 'Кошелек'), ('kaspi', 'Каспи')], max_length=15, null=True),
        ),
    ]
