# Generated by Django 4.2 on 2024-01-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
