# Generated by Django 4.2 on 2024-01-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_delete_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='identifier',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
