# Generated by Django 4.2 on 2024-01-18 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productimage_image'),
        ('order', '0012_myorder_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='returnorder',
            name='moder_comment',
        ),
        migrations.RemoveField(
            model_name='returnorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='returnorderproduct',
            name='returns_order',
        ),
        migrations.AddField(
            model_name='returnorderproduct',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='returnorderproduct',
            name='return_order',
            field=models.ForeignKey(default=466, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.returnorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_orders', to='order.myorder'),
        ),
        migrations.AlterField(
            model_name='returnorderproduct',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='returnorderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='returnorderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='product.asiaproduct'),
        ),
        migrations.CreateModel(
            name='ReturnOrderProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='return-products')),
                ('return_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='order.returnorderproduct')),
            ],
        ),
    ]
