# Generated by Django 4.2 on 2024-01-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_returnorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='identifier',
        ),
    ]
