# Generated by Django 4.2 on 2024-01-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_myorder_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorderproduct',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('success', 'success'), ('rejected', 'rejected')], default='created', max_length=8),
        ),
    ]
