# Generated by Django 4.2 on 2024-01-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_returnorderproduct_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnorder',
            options={'ordering': ('-created_at',)},
        ),
    ]
