# Generated by Django 4.2 on 2024-01-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_returnorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
