# Generated by Django 4.2 on 2024-01-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_myorder_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
