# Generated by Django 4.2 on 2024-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_remove_myorder_is_checked_orderproduct_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='uid',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=50),
        ),
    ]
