# Generated by Django 4.2 on 2024-03-04 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_alter_crmnotification_dealer_profiles'),
        ('general_service', '0006_alter_pricetype_options'),
        ('product', '0013_alter_asiaproduct_made_in'),
        ('order', '0021_returnorder_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('ab_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_order_products', to='product.asiaproduct')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.myorder')),
            ],
        ),
        migrations.CreateModel(
            name='MainOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('status', models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('sent', 'sent'), ('partial', 'partial'), ('rejected', 'rejected'), ('success', 'success')], default='created', max_length=15)),
                ('type_status', models.CharField(blank=True, choices=[('cash', 'Наличка'), ('visa', 'Виза'), ('wallet', 'Кошелек'), ('kaspi', 'Каспи')], max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_orders', to='account.dealerprofile')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_orders', to='general_service.stock')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
