# Generated by Django 4.2 on 2024-03-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_mainorderproduct_mainorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='main_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.mainorder'),
        ),
    ]
