# Generated by Django 4.2 on 2024-03-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_myorder_main_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainorderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.mainorder'),
        ),
    ]
