# Generated by Django 4.2 on 2024-04-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_remove_myorder_creator_mainorder_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainorder',
            name='payment_doc_uid',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=50),
        ),
    ]
